version: "3.8"

services:
  local_chain:
    image: ghcr.io/opentensor/subtensor-localnet:devnet-ready
    container_name: local_chain
    ports:
      - "9944:9944"
      - "9945:9945"
    volumes:
      - chain_data:/tmp

volumes:
  chain_data: