version: "3.8"

services:
  turbobt_shield_client:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm
    working_dir: /opt/long_running_test/manual_tests/
    volumes:
      - ../:/opt/long_running_test/
      - "$HOME/.bittensor:/root/.bittensor"
    command: uv run continously_run_turbobt_shield.py
  bittensor_shield_client:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm
    working_dir: /opt/long_running_test/manual_tests/
    volumes:
      - ../:/opt/long_running_test/
      - "$HOME/.bittensor:/root/.bittensor"
    command: uv run continously_run_shield_client.py
